# Heroes S, SS, SSR rank.
HEROES_3 = [
dict(id="S-1", name="Nerissa Pearlwhisper", epithet="the Moon-Tide Songstress", rank="S", race="Nereid", gender="female", age=36,
 body="graceful and full-figured, long legs, soft curves, delicate finned ears and wrists", size="Medium", height=170,
 element="Water", cls="Tide Singer", role="Support", pri="Charm", sec="Grace", room="Argent Market",
 look="Opalescent pale-blue skin with faint pearl scales on cheeks and shoulders, long silver-teal hair in floating braids, deep aqua eyes with glowing ring pupils, serene smile.",
 palette=["moon silver", "aqua", "pearl pink"],
 battle="Flowing silver-blue gown with a high thigh slit over fitted leggings, pearl-studded bodice, sheer layered sleeves with fin edges, silver bracers, a cape of floating water ribbons, silver trim along every hem.",
 casual="Loose silk wrap dress, bare feet with anklets, pearl hairpins, a glass of sea-mist tea.",
 work="Shopkeeper's silk vest and short skirt, pearl abacus beads at the hip.",
 weapon=("Moon-Tide Conch Harp", "A harp carved from a giant pearl-lined conch shell with silver strings that shimmer like moonlit water."),
 passive="Tide Song: heals the party a little whenever she plays a skill. Visual: drifting bubbles.",
 a1="Pearl Chord: heals one ally and cleanses. Visual: pearl ripple.",
 a2="Undertow Note: pulls an enemy forward. Visual: swirling water.",
 a3="Moonwash: shields the party. Visual: silver wave.",
 ult="Moon-Tide Requiem: a huge tide rises, healing allies and soaking enemies into slowness. Visual: a full moon over a crashing wave.",
 personality="Soothing, flirtatious, poised, secretly mischievous.",
 quote="Let the tide carry you. I'll hum.", origin="Singer from a drowned city who found a new stage at the Argent Market.",
 bg="Moonlit lagoon with glowing water and floating pearls."),
dict(id="S-2", name="Vesper Nightingale", epithet="the Silent Aria", rank="S", race="Dusk-kin (shadow fae)", gender="female", age=32,
 body="small, agile and delicately built, long legs, slim waist", size="Small", height=154,
 element="Dark", cls="Night Soloist Assassin", role="Striker", pri="Grace", sec="Charm", room="Deck Hall",
 look="Dark lavender skin, short sleek black hair with violet highlights, narrow silver eyes, small crescent-moon marks on the cheeks, calm mocking smile.",
 palette=["night violet", "silver", "black"],
 battle="Fitted black-violet bodysuit under a short layered skirt, silver-trimmed bolero, thigh-high boots with silver buckles, wing-like shadow ribbons, fingerless gloves, a silver mask pushed up on the head.",
 casual="Silk sleep shirt and shorts, thigh-high socks, cat-eared hood.",
 work="Stage-hand's vest with lanterns, tight shorts, soft shoes.",
 weapon=("Nightingale Needle Pair", "Two slender silver stilettos with violet glows along the edges and a ribbon of shadow wrapped at the hilt."),
 passive="Silent Aria: attacks from behind deal bonus damage and do not break stealth. Visual: shadow notes.",
 a1="Needle Aria: rapid two-hit strike. Visual: violet streaks.",
 a2="Curtain Fall: negates the next attack. Visual: a shadow curtain drops.",
 a3="Encore: repeats her last attack at reduced power. Visual: afterimage.",
 ult="Nocturne of Needles: a flurry through all enemies, finishing with a silent burst. Visual: scattered notes and a black moon.",
 personality="Cool, sly, theatrical, disarmingly kind to street cats.",
 quote="The finale is mine. Applause optional.", origin="Shadow fae who sang assassins to sleep before turning her blades on the court.",
 bg="Night theater stage, torn velvet curtains, violet spotlights."),
dict(id="S-3", name="Aeolus Brandt", epithet="the Pass-Warden", rank="S", race="Human (wind-touched)", gender="male", age=45,
 body="tall and powerfully built, broad chest, large hands, weathered", size="Large", height=206,
 element="Wind", cls="Windwall Warden", role="Tank", pri="Grit", sec="Might", room="Lumber Mill",
 look="Sun-tanned weathered face, long white-streaked brown hair braided back, pale silver eyes, a trimmed beard with small white feathers woven in, steady confident gaze.",
 palette=["storm grey", "silver", "teal"],
 battle="Heavy teal-trimmed mountain plate with silver filigree, fur-lined cloak, large pauldrons with wind-carved wing motifs, bracers, steel boots, a tower shield etched with wind spirals.",
 casual="Heavy knit sweater, trousers, scarf, mug of ale.",
 work="Rolled sleeves, log harness, leather apron.",
 weapon=("Brandt Gale-Tower Shield", "A giant tower shield of dull steel etched with wind spirals and white feather fringe; inside it hides a short-handled hammer."),
 passive="Wall of Wind: reduces projectile damage for the party. Visual: ripples of air around the shield.",
 a1="Gale Guard: gain a large shield and taunt. Visual: spiral of wind around him.",
 a2="Shield Gust: knock back and slow enemies. Visual: white gust cone.",
 a3="Updraft Slam: lifts an enemy and stuns. Visual: a spiraling uppercut.",
 ult="Pass of a Thousand Winds: a hurricane wall protects the party and shreds enemies at its edges. Visual: a spinning wind wall with silver streaks.",
 personality="Steady, proud, protective, a quiet wit.",
 quote="No storm gets past this gate.", origin="Warden of a windswept mountain pass who sealed it for ten winters alone.",
 bg="Windswept mountain pass, snow flurries, silver clouds."),
dict(id="S-4", name="TESSERAX-9 (Tess)", epithet="the Brass Dynamo", rank="S", race="Celestium Automaton", gender="nonbinary", age=27,
 body="compact, stocky humanoid frame of brass and silver plates with oversized hands, exposed coils at the joints, a glowing core in the chest", size="Small", height=140,
 element="Lightning", cls="Dynamo Savant", role="Controller", pri="Wit", sec="Sight", room="Deck Hall",
 look="A smooth porcelain-white face mask with a thin cyan visor, expressive glowing eyes, short copper-colored wire hair that sparks, gentle curious expression.",
 palette=["brass gold", "cyan", "white porcelain"],
 battle="Layered brass and silver armor plates with copper coils, a lightning-rod backpack, long cape of cables, gloves with glowing knuckles, a celestial blue core visible through the chest.",
 casual="Oversized cardigan over the chassis, slippers, a mug of oil-tea.",
 work="Tool-belt apron, rolled sleeves on a cardigan, goggles.",
 weapon=("Dynamo Coil Staff", "A long brass staff topped with a spinning tesla coil that crackles with blue-white arcs."),
 passive="Overclock: gains extra energy when an ally uses a Lightning skill. Visual: crackling blue sparks.",
 a1="Arc Lock: stuns one enemy. Visual: web of lightning.",
 a2="Capacitor: stores energy to boost the next skill. Visual: glowing coil.",
 a3="Chain Surge: hits multiple enemies. Visual: jumping arcs.",
 ult="Grand Dynamo Cascade: a massive field of chain lightning that stuns all enemies. Visual: a glowing coil tower and a sky of arcs.",
 personality="Curious, polite, collects odd facts, slightly bewildered by humor.",
 quote="Query: why is the party laughing? Updating.", origin="Automaton built to power a Celestium relay, awakened by the Heart's frequency.",
 bg="Brass-clockwork tower interior with glowing coils."),

dict(id="SS-1", name="Lumina 'Lumi' Starlit", epithet="the Constellation Weaver", rank="SS", race="Star-fae", gender="female", age=118,
 body="tiny, delicately built with long limbs, small star-shaped markings on shoulders", size="Small", height=140,
 element="Light", cls="Star Weaver", role="Support", pri="Charm", sec="Luck", room="Heart Sanctuary",
 look="Pale gold skin with a faint constellation freckle pattern, long flowing lavender-silver hair with glowing star tips, huge violet-gold eyes, warm excited smile, tiny star-shaped earrings.",
 palette=["starlight silver", "violet", "gold"],
 battle="Layered silver and violet short dress with a floating sash of stars, translucent sleeves, silver bracers, star-tipped boots, a trailing cape of constellation threads, refined silver-violet Celestium filigree all over.",
 casual="Oversized star-print sleep shirt, bare feet, glowing slippers.",
 work="Star-chart apron, tiny scissors-compass at the belt.",
 weapon=("Constellation Loom", "A floating loom-like ring of silver with strings of stars that she plucks and weaves into patterns."),
 passive="Starlight Thread: allies she buffs gain a small shield. Visual: tiny glowing threads.",
 a1="Weave Light: heals an ally and grants a regen. Visual: star threads stitch a wound.",
 a2="Star Seal: buffs the party's defense. Visual: constellation circle.",
 a3="Comet Stitch: Light damage to an enemy. Visual: shooting star.",
 ult="Grand Constellation: a giant starry web heals, shields and boosts all allies. Visual: a full-sky constellation unfolding.",
 personality="Giddy, kind, endlessly curious, easily distracted by shiny things.",
 quote="Look up! They're waving at us!", origin="Star-fae who traded her night-watch for the Heart's warm light.",
 bg="Star-filled twilight sky with aurora ribbons."),
dict(id="SS-2", name="Orsolya Granitecrown", epithet="the Mountain Queen", rank="SS", race="Half-giant", gender="female", age=55,
 body="powerfully built, broad shoulders and strong thighs, hourglass torso, strong arms", size="Medium", height=178,
 element="Earth", cls="Geo-Sovereign", role="Controller", pri="Wit", sec="Might", room="Stone Quarry",
 look="Warm brown skin with veins of faint gold, long silver-grey braid crowned with a ring of raw crystals, amber eyes, a confident half-smile, a small stone chip on one eyebrow.",
 palette=["granite grey", "gold", "amethyst violet"],
 battle="Regal armored robes of dark stone-gray and silver with violet gem inlay, cropped cape, sculpted pauldrons, fitted waist-belt, boots with stone-like greaves, a crown of crystals.",
 casual="Heavy velvet robe, house shoes, a mug of tea with raw crystals as sugar.",
 work="Geologist's coat with pockets of crystals, rolled sleeves.",
 weapon=("Granitecrown Scepter", "A tall scepter of black granite with silver bands and a cluster of violet crystal at the top."),
 passive="Crown of Stone: terrain effects also shield allies. Visual: crystals chime.",
 a1="Crystal Lock: roots and damages an enemy. Visual: crystals burst from the ground.",
 a2="Gem Barrier: shield on the party. Visual: floating gems.",
 a3="Sovereign Edict: lowers enemy defense. Visual: golden stone runes.",
 ult="Throne of the Mountain: raises a crystal throne that buffs allies and traps enemies. Visual: giant granite throne with glowing amethysts.",
 personality="Commanding, shrewd, gracious to underlings, loves gemstones.",
 quote="Kneel? No. But do be impressed.", origin="Half-giant ruler of a mountain hold who journeyed to see the Heart.",
 bg="Crystal throne hall inside a mountain, violet glow."),
dict(id="SS-3", name="Draven Emberlord", epithet="the Infernal Marshal", rank="SS", race="Demonkin", gender="male", age=39,
 body="large, powerfully muscled, broad chest and long horns, thick tail", size="Large", height=208,
 element="Fire", cls="Infernal Marshal", role="Striker", pri="Might", sec="Charm", room="The Forge",
 look="Dark red skin, long swept-back black hair with ember streaks, curved obsidian horns, glowing molten gold eyes, a sharp grin and a trimmed goatee.",
 palette=["crimson", "obsidian black", "silver-violet"],
 battle="Heavy black-and-crimson armor with silver and violet edge detailing, a long flaming cape, spiked pauldrons, a bare-armed combat stance with gauntlets, a tail guard, refined silver-violet Celestium trim glowing faintly.",
 casual="Open-collar silk shirt, tailored trousers, a goblet in hand, bare feet.",
 work="Leather smith apron, bare muscular arms, heat gauntlets.",
 weapon=("Emberlord Greatsword", "A huge obsidian greatsword with a molten crack running down the blade, silver-violet guard, and a fire-wrapped hilt."),
 passive="Infernal Might: each kill grants a stacking attack boost. Visual: flame crown.",
 a1="Hellfire Cleave: a wide Fire arc. Visual: crescent flame.",
 a2="Molten Guard: a counter stance that burns attackers. Visual: lava cracks.",
 a3="Marshal's Charge: dash and strike. Visual: trail of embers.",
 ult="Infernal Dominion: a huge demonic gate erupts, striking all enemies with fire. Visual: a hellgate with black flames.",
 personality="Charming, theatrical, ruthless in battle, fair with allies.",
 quote="Hell is a gentleman's hobby.", origin="Demon marshal who cast off his legion to fight for something warmer.",
 bg="Infernal forge hall, molten rivers, black flames."),
dict(id="SS-4", name="Thetis Maelstrom", epithet="the Abyssal Bulwark", rank="SS", race="Tidal titan (sea-giant)", gender="female", age=35,
 body="tall, broad and powerfully built, thick limbs, finned forearms", size="Large", height=212,
 element="Water", cls="Abyssal Bulwark", role="Tank", pri="Grit", sec="Might", room="Stone Well",
 look="Deep ocean-blue skin with bioluminescent teal markings, long dark teal hair like kelp, glowing silver-teal eyes, strong jaw, calm confident expression.",
 palette=["abyss blue", "bioluminescent teal", "silver-violet"],
 battle="Heavy coral-plate armor with silver-violet inlay, a bodice with sculpted wave patterns, long kelp-cape, large pauldrons shaped like shells, bracers with fins, greaves, a tower-shield made of a giant scallop shell with inner glowing Celestium crystals.",
 casual="Draped silk robes, bare feet, a shell necklace.",
 work="Waterman's rolled-sleeve tunic, rope belt, huge bucket yoke.",
 weapon=("Maelstrom Shell Bulwark", "A giant scallop-shell tower shield rimmed with silver, inner glow of violet-blue crystals; a spiral-shaped spear sits on the back."),
 passive="Pressure: reflects a portion of damage taken. Visual: whirlpool halo.",
 a1="Whirlpool Wall: massive party shield. Visual: spinning water.",
 a2="Pressure Slam: heavy Water hit that lowers enemy defense. Visual: crushing water burst.",
 a3="Undertow Spear: pulls and damages. Visual: a swirling trail.",
 ult="Maelstrom Aegis: a giant whirlpool protects the party and crushes enemies. Visual: a colossal spiral of water and pearls.",
 personality="Calm, protective, mischievous sense of humor, loves storms.",
 quote="Let the sea decide who passes.", origin="Titan guard of the abyssal gate who emerged when the Heart sang through the deep.",
 bg="Storm-tossed sea at dusk, giant whirlpool."),

dict(id="SSR-1", name="Elder Tuan Windshell", epithet="the Tortoise-Sage of Winds", rank="SSR", race="Tortoise-folk (wind-spirit)", gender="male", age=312,
 body="small, round and ancient, a large domed shell with swirling wind carvings, short sturdy limbs", size="Small", height=138,
 element="Wind", cls="Wind-Shell Sage", role="Tank", pri="Grit", sec="Wit", room="Heart Sanctuary",
 look="Wrinkled green-grey face with a beak-like mouth, long white whiskers, kind white-gold eyes, a tiny crown of drifting feathers, wind motes around the shell.",
 palette=["sage green", "silver", "celestium blue-violet"],
 battle="Ornate layered sage robes over a glowing shell, silver-engraved shell plates with floating Celestium crystals, a scarf of wind-ribbons, a gnarled staff with a floating crystal, small sandals.",
 casual="Tiny knitted shawl over the shell, slippers, a cup of tea balanced on the shell.",
 work="Sleeveless robe with a tea-tray, scrolls tucked into the shell.",
 weapon=("Windshell Crystal Staff", "A gnarled wooden staff with a floating contained Celestium crystal that spins with a spiral of wind."),
 passive="Ancient Shell: reduces all damage by a flat amount, increased by allies in front. Visual: wind carvings glowing.",
 a1="Shell Guard: giant shield for the party. Visual: shell lights up.",
 a2="Gale Lesson: cleanses debuffs and grants regen. Visual: gentle breeze.",
 a3="Tortoise Thump: Wind counter-strike. Visual: shockwave ring.",
 ult="Eternal Gale Sanctuary: a spherical wind barrier protects the party for three turns. Visual: a giant glowing shell dome of spiraling wind.",
 personality="Slow, wise, teasing, nap-prone, speaks in riddles and tea metaphors.",
 quote="Hurry less. The wind arrives anyway.", origin="Wind-spirit tortoise who sheltered the first travelers of Silverwood and answered the Heart.",
 bg="Sunlit mountain meadow with floating islands and wind swirls."),
dict(id="SSR-2", name="Solenne Auralis", epithet="the High Dawn Priestess", rank="SSR", race="Celestium-touched human", gender="female", age=38,
 body="tall and regal, graceful, defined shoulders, elegant long limbs", size="Medium", height=180,
 element="Light", cls="Dawn Priestess", role="Support", pri="Charm", sec="Grace", room="Heart Sanctuary",
 look="Luminous warm skin, long flowing white-gold hair with faint blue-violet strands, glowing gold eyes with a ring of Celestium blue, a serene commanding smile, small crystal crown.",
 palette=["radiant gold", "white", "celestium blue-violet"],
 battle="Long grand white and gold robes with a high leg slit over fitted leggings, ornate shoulder crown-pieces, contained Celestium crystals orbiting the arms, long sleeves with silver-violet filigree, a luminous halo, gold sandals.",
 casual="Soft ivory robe, loose hair, a cup of warm milk, reading a book.",
 work="Chapel apron over a robe, rolled sleeves, a rolling cart of herbs.",
 weapon=("Auralis Dawn Scepter", "A tall golden scepter topped with a contained Celestium crystal that radiates dawn-colored light; ribbons trail from it."),
 passive="Dawn's Blessing: full-HP allies gain a shield each turn. Visual: golden motes.",
 a1="Radiant Grace: large heal on one ally. Visual: a column of light.",
 a2="Crystal Ward: shields the party. Visual: orbiting crystals.",
 a3="Sunbreak: Light damage with a stun. Visual: a flare.",
 ult="Celestial Dawn: full heal, revives a fallen ally, grants huge attack. Visual: a massive sunrise with falling feathers of light.",
 personality="Compassionate, composed, subtly teasing, a firm will.",
 quote="Rise. The dawn has been waiting for you.", origin="High priestess who first felt the Heart wake and walked a thousand miles to meet it.",
 bg="A vast sunrise over clouds, golden light."),
dict(id="SSR-3", name="Erebus Nightcrown", epithet="the Void Regent", rank="SSR", race="Voidborn sovereign", gender="male", age=29,
 body="towering, tall and lean with long limbs, wisps of void-smoke trailing", size="Large", height=224,
 element="Dark", cls="Void Regent", role="Controller", pri="Wit", sec="Charm", room="Heart Sanctuary",
 look="Pale violet-grey skin with star-like specks across the face, long flowing black hair with a violet gradient, glowing violet eyes, a calm sovereign smile, a faint crown of black crystals.",
 palette=["void black", "violet", "celestium silver-blue"],
 battle="Layered black-and-violet royal robes with a high collar and long cape of void-smoke, ornate silver-violet filigree, fitted armored vest, gauntlets, tall boots, contained Celestium crystals orbiting the shoulders like black stars.",
 casual="Silk dressing gown, loose hair, a goblet of dark tea, bare feet.",
 work="Scribe's apron over fine clothes, rolled sleeves, scrolls and ink.",
 weapon=("Nightcrown Void Scepter", "A tall black scepter with a floating void-crystal at the top, wrapped by violet ribbons and slow orbiting stars."),
 passive="Regent's Domain: enemies' buffs last one turn less. Visual: a ring of void sigils on the floor.",
 a1="Void Chain: roots and weakens one enemy. Visual: black chains with violet sparks.",
 a2="Royal Decree: lowers attack of all enemies. Visual: dark sigil in the sky.",
 a3="Starfall Shard: Dark hit that ignores some defense. Visual: black shooting star.",
 ult="Throne of the Abyss: opens a void gate that pulls enemies in, stuns and deals massive damage. Visual: a colossal black crown above a swirling void.",
 personality="Elegant, calm, secretly lonely, shows kindness in odd ways.",
 quote="Kneel only if you wish. The void will wait.", origin="Prince of the void who rejected his throne after hearing the Heart's warm hum.",
 bg="Starless void palace with black crystals and violet glow."),
dict(id="SSR-4", name="Ragnhild Thunderveil", epithet="the Valkyrie of the Storm", rank="SSR", race="Valkyrie (storm-kin)", gender="female", age=34,
 body="tall, athletic and powerfully built, defined arms and legs, broad shoulders", size="Large", height=205,
 element="Lightning", cls="Storm Valkyrie", role="Striker", pri="Might", sec="Grace", room="The Forge",
 look="Fair skin with faint blue lightning-vein markings, long braided platinum hair with silver rings, bright electric-blue eyes, a fierce confident grin, a small scar across the cheek.",
 palette=["storm blue", "silver", "celestium violet"],
 battle="Fitted storm-blue and silver Valkyrie armor with a short flared skirt over thigh plates, winged helm crest, shoulder-pieces with contained Celestium crystals, long cape crackling with lightning, tall winged boots, bare midriff armor lattice, gauntlets.",
 casual="Fur-trimmed cloak over a casual sleeveless top and leggings, boots, a horn of mead.",
 work="Forge-yard sparring trainer's gear: sleeveless top, shorts, shoulder guard, leather wrist wraps.",
 weapon=("Thunderveil Spear", "A long silver spear with a lightning-forked tip, a contained Celestium crystal in the shaft, and wing-shaped crossguard."),
 passive="Stormborne: every action adds charge; at 5 charge, the next attack is a lightning strike. Visual: crackling aura.",
 a1="Thunder Thrust: piercing Lightning hit. Visual: forked bolt along the spear.",
 a2="Valkyrie's Leap: jump strike hitting two enemies. Visual: arcing silhouette.",
 a3="Storm Veil: evasion and counter. Visual: cloak of lightning.",
 ult="Ragnarok Descent: she rides a lightning bolt down onto the enemy line, exploding in a massive storm. Visual: a gigantic Valkyrie silhouette and bolts splitting the sky.",
 personality="Bold, loud, protective, loves a good feast.",
 quote="Let the storm sing our names!", origin="Valkyrie who followed a storm to the Heart and swore her spear to the Summoner.",
 bg="Stormy mountaintop, lightning forks, wind-swept clouds."),
]
