# Heroes F, E, D rank. Fields documented in build_prompts.py.
HEROES_1 = [
dict(id="F-1", name="Pip Thistlewick", epithet="the Tinker-Trapper", rank="F", race="Gnome", gender="male", age=29,
 body="round-bellied and wiry, long nimble fingers, oversized ears", size="Small", height=128,
 element="Earth", cls="Tinker-Trapper", role="Controller", pri="Wit", sec="Grit", room="Stone Quarry",
 look="Freckled round face, gap-toothed grin, messy sand-brown hair tied with a wire, big hazel eyes behind brass-rimmed goggles pushed up on the forehead, soot smudge on one cheek.",
 palette=["worn denim blue", "rust orange", "dull brass"],
 battle="Patched canvas overalls with a leather chest rig of spring-loaded gadgets, thick work gloves, goggles down over the eyes, knee pads, oversized tool belt.",
 casual="Rolled-sleeve flannel shirt, suspenders, rolled trousers, mismatched socks and slippers, a pencil behind one ear.",
 work="Quarry apron over a sleeveless shirt, tool roll on the hip, dust mask hanging at the neck, sturdy short boots.",
 weapon=("Rattle-Snare Crossbow", "A stubby wooden crossbow with a hand-crank winch, coiled snare-wire spool, and a cracked brass pressure gauge; clearly homemade."),
 passive="Tinkerer's Luck: first trap each battle costs no AP. Visual: tiny gears spin out of the belt.",
 a1="Snap Snare: roots one enemy in place for a turn. Visual: wire loops burst from the ground.",
 a2="Pebble Volley: three weak Earth shots across the enemy line. Visual: gravel pellets from the crossbow.",
 a3="Jury-Rig: repairs ally shield value, small. Visual: wrench swings, sparks and tape.",
 ult="Great Big Trap Bonanza: a field of snares and spring boards locks the whole enemy line. Visual: a comical contraption erupts from the earth with cogs and springs.",
 personality="Nervous, inventive, talks to his gadgets, overly proud of tiny victories.",
 quote="It only exploded a little!", origin="Quarry-town mender who built traps to keep wolves off the pumpkin patch.",
 bg="Dusty quarry workshop, lantern light, hanging tools, scrap-metal clutter."),
dict(id="F-2", name="Bram Oakhelm", epithet="the Barn-Door Shield", rank="F", race="Human", gender="male", age=34,
 body="barrel-chested, thick-armed farmhand, broad and slightly soft, big hands", size="Large", height=192,
 element="Water", cls="Shieldbearer", role="Tank", pri="Grit", sec="Might", room="Stone Well",
 look="Square sunburnt face, short curly black hair, thick eyebrows, warm brown eyes, stubble, a crooked nose from a mule kick.",
 palette=["faded moss green", "wet-slate blue", "plain leather brown"],
 battle="Padded gambeson over a farm shirt, patched leather pauldron on one shoulder, wooden bucket-lid vambrace, thick belt, heavy boots; carries an old barn-door as a shield.",
 casual="Undyed linen shirt with rolled sleeves, braces, straw hat, mud-brown trousers.",
 work="Sleeveless well-keeper tunic, rope belt, two water pails on a yoke, heavy boots.",
 weapon=("Barn-Door Shield", "A battered oak barn door cut into a tower shield, iron hinges still attached, painted blue rain-drops by a child."),
 passive="Stubborn as a Mule: takes 10% less damage while below half HP. Visual: a faint blue ripple around the shield.",
 a1="Brace: gain shield and taunt for a turn. Visual: plants the door, ripple of water.",
 a2="Bucket Brigade: splash heals ally slightly. Visual: tosses a pail of water over a friend.",
 a3="Shoulder Shove: pushes enemy back and lowers its next attack. Visual: door slams forward.",
 ult="Flood Gate: a wall of water forms behind the shield, absorbing damage for the whole party. Visual: the barn door swings open, torrent surges.",
 personality="Quiet, dependable, gently humorous, dislikes violence, loves his mule.",
 quote="Stand behind me. I've got a door.", origin="Farmhand who defended a well from raiders with the nearest thing he owned.",
 bg="Rain-soaked farmyard at dawn, wooden barn, puddles reflecting lantern light."),
dict(id="F-3", name="Tilly Nettlebright", epithet="the Fenceline Runner", rank="F", race="Human", gender="female", age=24,
 body="lean long-legged sprinter, small chest, narrow hips, scuffed knees", size="Medium", height=165,
 element="Wind", cls="Skirmisher", role="Striker", pri="Grace", sec="Luck", room="Silverbrook Adventure Guild",
 look="Heart-shaped face, sharp grin, windswept chestnut ponytail with a green ribbon, bright green eyes, freckles across the nose, a small scar on the chin.",
 palette=["meadow green", "cream", "tan leather"],
 battle="Short leather jerkin, fitted sleeveless tunic, short wrap skirt over biker shorts, bracers, light running boots, green scarf trailing behind.",
 casual="Oversized knit sweater slipping off one shoulder, leggings, comfy boots, ribbon in her hair.",
 work="Courier satchel with guild badge, sleeveless vest, fitted shorts, sturdy sneakers-style boots.",
 weapon=("Hedge Clippers & Dagger", "A pair of oversized garden shears reforged into twin short blades with green cord-wrapped handles."),
 passive="Fleet Feet: acts first on turn one. Visual: green dust trail at her heels.",
 a1="Dash Cut: strike and reposition behind the line. Visual: afterimage streak.",
 a2="Gust Step: dodge next attack. Visual: a wind swirl lifts her scarf.",
 a3="Hedge Slash: hits two enemies for modest damage. Visual: crossing green arcs.",
 ult="Hundred Fence Dash: a rapid-fire run through all enemies, hitting each once. Visual: a blur of green slashes and falling leaves.",
 personality="Cheeky, restless, loyal, hates being told to wait.",
 quote="Catch me if you can. Spoiler: you can't.", origin="Runner who delivered messages between farms and dared the forest edge for shortcuts.",
 bg="Windy grass slope under a fence line, scattered leaves, wide sky."),
dict(id="F-4", name="Rook Emberwick", epithet="the Hearth Kobold", rank="F", race="Kobold (lizardfolk)", gender="male", age=31,
 body="slender small reptilian frame, long tail, digitigrade legs, expressive frilled ears", size="Small", height=140,
 element="Fire", cls="Hearth Tender", role="Support", pri="Charm", sec="Grace", room="Kitchen",
 look="Orange-scaled snout with a cream belly, warm amber slit-pupil eyes, small swept-back horns, tiny soot freckles, a toothy anxious smile.",
 palette=["ember orange", "cream", "soot grey"],
 battle="Oversized apron-vest with a banner of scorched cloth, mitts, leather leg wraps, tail ring, ladle-staff carried like a spear.",
 casual="Soft knitted vest, shorts, scarf wrapped around the horns, slippers.",
 work="Cook's apron, rolled sleeves, oven mitts on belt, a flour smudge.",
 weapon=("Ember Ladle", "A long iron ladle with a hollow bowl that holds a tiny glowing coal, wrapped with colored yarn."),
 passive="Warm Hands: allies he heals also gain a little ongoing warmth regen. Visual: soft orange glow.",
 a1="Stoke: gives an ally an energy boost. Visual: coals flare from the ladle.",
 a2="Soup Splash: heals a small amount. Visual: a ladle swing of steaming broth.",
 a3="Cinder Pop: weak Fire hit on an enemy. Visual: sparks from the ladle bowl.",
 ult="Hearth Feast: a big communal meal heals the whole party and boosts morale. Visual: a bubbling cauldron of golden light, steaming bowls appear.",
 personality="Timid, warm, nurturing, apologizes constantly, secretly brave when friends are hurt.",
 quote="S-sorry, but also, soup?", origin="Orphaned kobold who found safety tending the Silverbrook hearth.",
 bg="Cozy rustic kitchen, glowing hearth, hanging herbs and copper pots."),

dict(id="E-1", name="Zippa Sparkwhisker", epithet="the Storm Courier", rank="E", race="Marten-folk (beastfolk)", gender="female", age=26,
 body="small, sleek and agile, long sinuous tail, slender limbs, tiny rounded ears", size="Small", height=150,
 element="Lightning", cls="Courier", role="Striker", pri="Grace", sec="Luck", room="Silverbrook Adventure Guild",
 look="Cream-furred muzzle with mahogany-brown fur, bright yellow eyes with lightning-bolt pupils when excited, whiskers that spark, messy short dark hair, quick sharp smile.",
 palette=["storm yellow", "charcoal brown", "white"],
 battle="Light leather harness over a sleeveless tunic, bandolier of message tubes, short pleated skirt over bike shorts, fingerless gloves, rubber-soled boots, a lightning-bolt patch.",
 casual="Hooded oversized jacket, shorts, striped knee socks, earphone-like copper rings on the ears.",
 work="Courier cap, satchel strap across the chest, fitted tank top, short pants.",
 weapon=("Copper Rod Daggers", "Two short copper rods with insulated rubber grips and sparking tips, linked by a thin chain."),
 passive="Static Build: each action adds a spark stack, increasing next hit. Visual: crackling hair.",
 a1="Spark Jab: fast Lightning stab. Visual: yellow flash.",
 a2="Chain Zip: hits two enemies. Visual: arcs jumping between them.",
 a3="Short Circuit: lowers an enemy's speed. Visual: blue static coils.",
 ult="Thunderline Express: dashes through every enemy in a zigzag lightning trail. Visual: a long glowing bolt path with message scrolls fluttering.",
 personality="Talkative, reckless, fiercely loyal, hates standing still.",
 quote="Delivery! Signed, sealed, shocked!", origin="Fastest courier between the foothill hamlets before the Heart called her.",
 bg="Stormy ridge at dusk, electric clouds, a rope bridge."),
dict(id="E-2", name="Sister Calla Dawnmend", epithet="the Gentle Lamp", rank="E", race="Human", gender="female", age=31,
 body="soft, sturdy and warm, generous curves, strong forearms from tending patients", size="Medium", height=168,
 element="Light", cls="Lamp Priest", role="Support", pri="Grace", sec="Charm", room="The Frosted Mug",
 look="Round kind face, short honey-blonde hair under a veil, hazel eyes with crow's feet, rosy cheeks, a gentle patient smile.",
 palette=["warm cream", "pale gold", "soft rose"],
 battle="Long white robe with a practical short side-slit over leggings, quilted gold-trim vest, bandage satchel, sandals with leg wraps, a lamp hung at the belt.",
 casual="Lavender knitted shawl over a plain dress, slippers, reading glasses on a chain.",
 work="Medic apron over a plain dress, sleeves rolled, herb pouch.",
 weapon=("Dawn Lantern Staff", "A wooden staff topped with a small brass lantern holding a steady warm flame that never burns."),
 passive="Warm Glow: heals the lowest-HP ally slightly at turn start. Visual: soft golden motes.",
 a1="Mend: heals one ally. Visual: lamp light pours over a wound.",
 a2="Bless: removes one weak debuff. Visual: golden ring.",
 a3="Lantern Flash: blinds enemies for a turn. Visual: a sudden bright flare.",
 ult="Dawn Embrace: a warm light heals everyone and raises shield. Visual: a sunrise bursts behind her.",
 personality="Patient, practical, hums while she works, firm bedside manner.",
 quote="Drink. Rest. Then we talk about being brave.", origin="Chapel lamp-keeper who tended wounded travelers on the forest road.",
 bg="Candlelit chapel infirmary at dawn, cots, hanging herbs."),
dict(id="E-3", name="Mordecai Gloam", epithet="the Hollow Gravedigger", rank="E", race="Shade-touched human", gender="male", age=38,
 body="tall, gaunt and lanky, stooped shoulders, long fingers", size="Large", height=198,
 element="Dark", cls="Hexer", role="Controller", pri="Wit", sec="Sight", room="Deck Hall",
 look="Long pale face with dark circles, black hair tied back loosely, one violet-grey eye and one dull black eye, thin smile, shadow pooling at his feet.",
 palette=["charcoal", "ash purple", "bone white"],
 battle="Long dark work coat with patched elbows, high-collared shirt, fingerless gloves, cloth wraps on the shins, a rope belt with small charms and coins.",
 casual="Loose open collar shirt, vest, slouchy trousers, a scarf, barefoot slippers.",
 work="Shirtsleeves rolled, leather apron, grave-spade on the back.",
 weapon=("Gravedigger's Spade", "A long iron-headed shovel with black ribbon tied at the haft and small bone charms."),
 passive="Hollow Presence: enemies he afflicts have slightly lowered accuracy. Visual: a faint shadow haze.",
 a1="Hex Mark: marks an enemy, increasing damage it takes. Visual: dark sigil.",
 a2="Grave Chill: slows two enemies. Visual: frost-like shadows from the ground.",
 a3="Spade Swing: heavy Dark hit. Visual: wide arc with black ribbon.",
 ult="Quiet Earth: a ring of shadow hands pins all enemies. Visual: dozens of dark hands rising from graves.",
 personality="Dry, gentle, morbid humor, kind to children, speaks softly.",
 quote="Everyone gets a quiet place. Let me show you yours.", origin="Village gravedigger who learned the dead keep secrets worth hearing.",
 bg="Moonlit hillside graveyard, mist, crooked headstones."),
dict(id="E-4", name="Ulric Cairnbreaker", epithet="the Steady Stone", rank="E", race="Dwarf", gender="male", age=52,
 body="short, very broad and densely muscled, thick limbs, big belly, powerful hands", size="Small", height=140,
 element="Earth", cls="Wall Miner", role="Tank", pri="Grit", sec="Might", room="Stone Quarry",
 look="Weathered ruddy face, huge braided grey-brown beard with metal rings, bushy brows, dark brown eyes, stone dust in the hair.",
 palette=["slate grey", "rust red", "iron black"],
 battle="Thick leather jerkin with iron plates riveted on, studded bracers, heavy canvas trousers, steel-toed boots, mining helmet with dull lamp.",
 casual="Heavy wool sweater, apron-less, mug-stained trousers, house boots.",
 work="Open sleeveless work vest, rolled sleeves, pickaxe strapped across the back, dust cloth at the neck.",
 weapon=("Cairn Pick & Tower Plate", "A sturdy two-handed pickaxe with an iron head and a half-moon rock-plate shield strapped to the left arm."),
 passive="Rock Steady: cannot be pushed or knocked back. Visual: small stone spikes anchor his boots.",
 a1="Granite Guard: gain a large shield. Visual: stone plates slide up.",
 a2="Pick Breaker: heavy hit that lowers enemy defense. Visual: cracking ground.",
 a3="Tremor Stomp: staggers the enemy line. Visual: shockwave in the dust.",
 ult="Mountainheart: becomes nearly immune for two turns and taunts all enemies. Visual: a stone shell forms around him.",
 personality="Gruff, patient, fond of stories, secretly sentimental.",
 quote="Lean on me, lad. I've been leaned on by mountains.", origin="Retired mine foreman called back to hold the line for the tower.",
 bg="Lamp-lit cave mine, timber supports, glittering ore."),

dict(id="D-1", name="Ashlyn Cinderbraid", epithet="the Ember Duelist", rank="D", race="Tiefling", gender="female", age=27,
 body="athletic and toned, long legs, defined shoulders, curved horns", size="Medium", height=172,
 element="Fire", cls="Duelist", role="Striker", pri="Might", sec="Charm", room="The Forge",
 look="Warm bronze-red skin, sharp cheekbones, long red-black braided hair with ember sparks, small swept horns, golden slit-pupil eyes, a confident smirk, tail with a ruby tip.",
 palette=["ember red", "gunmetal", "gold"],
 battle="Fitted dark red leather corset-jacket over a fitted top, short asymmetric skirt over shorts, steel pauldron on one shoulder, tall boots with ember trim, tail ring.",
 casual="Off-shoulder cropped sweater, high-waisted trousers, loose braid, small gold hoops.",
 work="Forge apron over a tank top, heat gloves, tied-back braid.",
 weapon=("Cindersong Rapier", "A slender rapier with a glowing ember-orange blade edge, a swept-hilt guard shaped like flame, and a red ribbon tied at the pommel."),
 passive="Kindling: each Fire hit raises the next Fire hit by 10%. Visual: embers trailing the blade.",
 a1="Ember Lunge: fast thrust. Visual: flare along the line of the blade.",
 a2="Spark Parry: counter the next attack. Visual: sparks at the guard.",
 a3="Brand: burn enemy for damage over time. Visual: glowing sigil on the foe.",
 ult="Phoenix Flourish: five rapid thrusts ending in a rising flame arc. Visual: wings of fire behind her.",
 personality="Proud, flirtatious, competitive, fiercely protective of apprentices.",
 quote="Try to keep up. I do burn bright.", origin="Duelist-for-hire who paid off a forge debt and stayed to guard it.",
 bg="Forge floor with glowing coals, sparks swirling, anvil in shadow."),
dict(id="D-2", name="Juniper Gale", epithet="the Windsprite Warden", rank="D", race="Sprite-kin (fae)", gender="female", age=140,
 body="tiny delicate frame, long limbs relative to body, translucent leaf-veined ear-fins", size="Small", height=145,
 element="Wind", cls="Windwarden", role="Controller", pri="Wit", sec="Sight", room="Deck Hall",
 look="Pale green skin with faint leaf veins, silver-white asymmetric bob with moss tufts, large teal eyes, dragonfly-wing hairpins, mischievous smile.",
 palette=["pale teal", "silver", "moss green"],
 battle="Layered leaf-cut tunic with a flowing cape, strap harness, bracers carved with spirals, slim leggings, soft boots with feather trim.",
 casual="Oversized linen shirt as a dress, sandals, daisy crown.",
 work="Strategist's feathered sash, light vest, shorts, a tiny chime pinned to a clipboard of wind-charts.",
 weapon=("Gale Chimes", "A pair of small hanging bell-chimes on a hooked staff that ring with the wind and draw faint glowing spirals."),
 passive="Updraft: allies in her row have a small evasion boost. Visual: leaves drift upward.",
 a1="Chime Shield: shields an ally. Visual: swirling bell ring.",
 a2="Crosswind: pushes enemies out of position. Visual: sweeping gust lines.",
 a3="Mist Lure: confuses one enemy. Visual: glowing spiral fog.",
 ult="Hurricane Hymn: all enemies are blown to the back and slowed. Visual: a large spiral of leaves and notes.",
 personality="Playful, sharp-tongued, bores easily, deeply attentive when it counts.",
 quote="Listen. The wind is gossiping about you.", origin="Forest sprite who guarded a wind-shrine until the tower's crystal began to hum.",
 bg="Canopy of tall pines, wind-swept clearing, floating seeds."),
dict(id="D-3", name="Tarn Deepcurrent", epithet="the River Bulwark", rank="D", race="Saurian (lizardfolk)", gender="male", age=40,
 body="huge, thick-tailed and broad-shouldered, heavy plated back, powerful legs", size="Large", height=205,
 element="Water", cls="Bulwark", role="Tank", pri="Grit", sec="Might", room="Stone Well",
 look="Teal-green scales, cream throat, ridged brow, deep gold eyes, short frill crest, a notched fin on one ear, calm patient expression.",
 palette=["river teal", "gunmetal", "bone"],
 battle="Layered scale-mail kilt, bronze chest plate with water motif, heavy gauntlets with tidal engraving, a rope belt with shells, bare clawed feet with ankle wraps.",
 casual="Open wool tunic, sash, sandals, a woven fishing hat.",
 work="Sleeveless leather vest, hip waders, bucket and rope.",
 weapon=("Riverbend Maul", "A long-handled maul with a smooth river stone head bound in bronze wire and etched current patterns."),
 passive="Deep Calm: gains a shield each time an ally is hit. Visual: a gentle blue ripple.",
 a1="Tide Wall: large shield for him. Visual: water sheet rises.",
 a2="Undertow: pulls enemies to the front and lowers their speed. Visual: a swirl at their feet.",
 a3="Maul Crash: heavy Water hit. Visual: splash ring.",
 ult="Flood Bulwark: a wave surrounds the party, giving shield and healing over time. Visual: a rising wall of crystalline water.",
 personality="Patient, deliberate, deeply loyal, enjoys fishing and silence.",
 quote="Let them come. The river has all day.", origin="River-guardian of a ford who accepted the tower's call to protect travelers.",
 bg="Misty river ford at dawn, stones, slow water."),
dict(id="D-4", name="Brother Isidore Lumen", epithet="the Hollow-Eyed Monk", rank="D", race="Human", gender="male", age=45,
 body="gaunt, tall-ish and wiry, long neck, prominent collarbones, calloused hands", size="Medium", height=180,
 element="Light", cls="Lightmonk", role="Support", pri="Wit", sec="Grace", room="Deck Hall",
 look="Shaved head with fine silver stubble, deep-set pale blue eyes ringed with fatigue, serene half-smile, a light scar across the brow.",
 palette=["sandstone", "pale gold", "indigo"],
 battle="Layered monk robes with one shoulder bare, wrapped forearms, sash with prayer beads, simple sandals, a halo-like ring of light behind the head.",
 casual="Plain sleeping robe, shawl, tea cup in hand.",
 work="Scribe's sleeves and ink-stained apron, prayer beads at the wrist.",
 weapon=("Prayer-Bead Chain", "A long chain of wooden prayer beads with a small brass sun medallion at the end, used as a whip and focus."),
 passive="Inner Calm: gains energy when an ally is healed. Visual: faint sunbursts.",
 a1="Radiant Strike: Light hit with the chain. Visual: golden whip arc.",
 a2="Ward of Beads: shield one ally. Visual: floating beads circle.",
 a3="Clarity: cleanses a debuff. Visual: soft sunlight.",
 ult="Hundred Lights: scatters beads that heal the party and strike enemies. Visual: a rain of glowing bead-lights.",
 personality="Soft-spoken, dryly funny, obsessed with tea and small kindnesses.",
 quote="Breathe. Then strike where the light falls.", origin="Monk who left a mountain cloister to teach battlefield calm.",
 bg="Sunlit cloister courtyard with stone arches and drifting dust motes."),
]
