# Heroes C, B, A rank.
HEROES_2 = [
dict(id="C-1", name="Nyx Veilwhisper", epithet="the Dusk Knife", rank="C", race="Dusk-elf", gender="female", age=95,
 body="slight and flexible, narrow shoulders, long slender legs, pointed ears", size="Small", height=154,
 element="Dark", cls="Shadowblade", role="Striker", pri="Grace", sec="Sight", room="Silverbrook Adventure Guild",
 look="Deep violet-grey skin, white-silver blunt bob with a long side fringe, glowing magenta eyes, a faint star-freckle pattern across the cheeks, sly closed-mouth smile.",
 palette=["midnight violet", "silver", "black"],
 battle="Fitted dark leather cuirass with a high collar, cropped cape, asymmetric short skirt over thigh-high wraps, knife harness across the hips, black boots with silver buckles, a half-face scarf.",
 casual="Oversized dark hoodie, shorts, striped thigh-high socks, silver stud earrings.",
 work="Courier-style vest and shorts, knife roll folded at the belt.",
 weapon=("Veilknife Pair", "Two curved black-steel daggers with violet edge-glints and ribbon-wrapped grips; their shadows move a moment late."),
 passive="Slip Into Shade: first attack each turn ignores a taunt. Visual: her silhouette blurs.",
 a1="Shadow Step: teleport behind an enemy and strike. Visual: violet mist.",
 a2="Silent Cut: bonus damage to debuffed enemies. Visual: thin slash lines.",
 a3="Smoke Veil: evade next attack. Visual: black smoke coil.",
 ult="Eclipse Dance: a series of unseen cuts through all enemies. Visual: darkness sweeps the stage, only knife glints show.",
 personality="Quiet, wry, loyal to a handful of people, hates crowds.",
 quote="You never saw me. That was the plan.", origin="Dusk-elf scout banished for refusing to burn a village, hired by the Guild.",
 bg="Moonlit rooftop in a misty town, crooked chimneys, violet clouds."),
dict(id="C-2", name="Captain Rhea Stormhail", epithet="the Banner Captain", rank="C", race="Human", gender="female", age=36,
 body="tall, strongly built with broad shoulders and an upright stance", size="Medium", height=174,
 element="Lightning", cls="Banner Captain", role="Support", pri="Charm", sec="Might", room="Silverbrook Adventure Guild",
 look="Square strong jaw, short dark curly hair with a grey streak, bright steel-blue eyes, a scar through the left eyebrow, confident grin.",
 palette=["storm blue", "silver", "crimson"],
 battle="Blue officer coat with silver epaulettes over fitted plate cuirass, short pleated skirt over trousers, tall boots, long cape, a banner pole slung across the back.",
 casual="Open-collar shirt, suspenders, rolled sleeves, a mug of cocoa.",
 work="Captain's vest with rolled sleeves and clipboard.",
 weapon=("Stormhail Standard", "A long banner-spear with a storm-blue pennant crackling with static and a silver lightning bolt tip."),
 passive="Rally: allies gain energy at turn start if the banner is planted. Visual: pennant sparks.",
 a1="Plant Standard: grants all allies a small attack bonus. Visual: banner slams into ground.",
 a2="Crack Orders: grants an ally an extra action. Visual: a lightning snap.",
 a3="Spear Jolt: Lightning hit that jumps to a second enemy. Visual: arc along the spear.",
 ult="Storm Charge: the whole party gets speed and attack boosts. Visual: banner raised, lightning striking behind.",
 personality="Commanding, warm, speeches with dry humor, never abandons the wounded.",
 quote="On your feet. The storm's with us.", origin="Mercenary captain who lost her company and found a new one at the Gate.",
 bg="Windswept hilltop, banners snapping, storm clouds."),
dict(id="C-3", name="Torvald Greywall", epithet="the Walking Cliff", rank="C", race="Goliath", gender="male", age=41,
 body="mountainous and broad with massive arms and a thick neck", size="Large", height=218,
 element="Earth", cls="Cliff Guardian", role="Tank", pri="Grit", sec="Might", room="Lumber Mill",
 look="Grey stone-textured skin with pale rune-like markings, shaved head, heavy brow, glowing amber eyes, braided grey beard, a calm stoic expression.",
 palette=["granite grey", "moss green", "bronze"],
 battle="Heavy plate pauldrons carved with striations, a wide leather harness, iron-banded kilt, bracers, stone-wrapped greaves, a moss-lined cape.",
 casual="Huge knit vest, woolen trousers, slippers, a toy carved for a child in hand.",
 work="Rolled-sleeve work shirt, log harness, heavy gloves.",
 weapon=("Grey Wall Maul", "A huge stone-headed maul wrapped with iron bands and carved with climbing vines."),
 passive="Immovable: reduces damage from the first hit each turn. Visual: stone plates glinting.",
 a1="Cliff Stance: massive shield and taunt. Visual: stone rises around him.",
 a2="Boulder Throw: ranged Earth damage. Visual: a thrown rock.",
 a3="Quake Step: stuns the front enemy. Visual: crack through the ground.",
 ult="Avalanche Guard: shields all allies and counters the next attack. Visual: falling boulders form a wall.",
 personality="Slow to speak, gentle with small creatures, immovable on principle.",
 quote="I do not move. You do.", origin="Mountain-herd guardian who descended after the Heart's call echoed through the stone.",
 bg="Rocky mountain pass with mossy boulders and mist."),
dict(id="C-4", name="Marisol Pyreheart", epithet="the Alchemist of Smoke", rank="C", race="Human", gender="female", age=30,
 body="hourglass figure, strong thighs, small waist, curvy proportions", size="Medium", height=170,
 element="Fire", cls="Pyro-Alchemist", role="Controller", pri="Wit", sec="Luck", room="The Frosted Mug",
 look="Warm brown skin, thick curly black hair in a loose bun with burn-singed ends, amber eyes with a clever glint, beauty mark by the lip, smirking.",
 palette=["amber", "burnt orange", "bronze"],
 battle="Fitted burgundy leather corset-vest over a white blouse, short pleated skirt over leggings, bandolier of vials, goggles on the forehead, singed apron-cape, tall boots.",
 casual="Silk robe over a camisole, fluffy slippers, hair wrapped in a towel.",
 work="Apron over a tank top and shorts, singed gloves, bottles on the belt.",
 weapon=("Smoke-Vial Bandolier", "A leather bandolier of corked vials glowing with orange, green and violet fumes, plus a long brass tongs."),
 passive="Volatile Mix: debuffs from her potions last one turn longer. Visual: swirling smoke.",
 a1="Flash Flask: blinds and burns. Visual: orange burst.",
 a2="Sticky Resin: slows enemies. Visual: glowing tar.",
 a3="Quick Brew: gives an ally energy. Visual: bubbling vial.",
 ult="Grand Combustion: a massive controlled explosion with lingering fire. Visual: a plume with colored smoke rings.",
 personality="Brilliant, sarcastic, careless about safety, generous with friends.",
 quote="Don't touch that. Okay, touch that one.", origin="Alchemist whose lab burned down three times; the Frosted Mug gave her a fourth.",
 bg="Cluttered alchemy lab, bubbling beakers, glowing smoke."),

dict(id="B-1", name="Kestrel", epithet="the Fireblade", rank="B", race="Human", gender="female", age=27,
 body="compact, wiry and athletic, powerful shoulders, short legs, quick stance", size="Small", height=156,
 element="Fire", cls="Twin-Blade Vanguard", role="Striker", pri="Might", sec="Grace", room="The Forge",
 look="Fierce, bright red hair in a short high ponytail, warm amber eyes, small scar on the chin, a determined grin, red war paint streaks under the eyes. Canon: first card drawn; direct, brave, impatient with indecision.",
 palette=["ember red", "dark steel", "cream"],
 battle="Fitted crimson and black battle jacket with a cropped midriff, steel pauldrons, short pleated skirt over thick shorts, tall boots, twin sheaths on the hips, a faint blue-silver Celestium thread in the trim.",
 casual="Sleeveless hoodie, track shorts, scarf, sandals.",
 work="Forge apron over a sports top and shorts, heat gloves.",
 weapon=("Twin Cinder Blades", "Two short swords with matching ember-glow edges, black steel and red cord grips, a hairline of blue-silver Celestium inlay near the guard."),
 passive="First Draw: opening-turn attacks deal bonus damage. Visual: blades flare red.",
 a1="Ember Cross: crossing slashes. Visual: X-shaped flame.",
 a2="Heat Surge: gain energy when she takes damage. Visual: flaring aura.",
 a3="Blade Rush: charge through the front line. Visual: horizontal fire streak.",
 ult="Fallen Gate: a huge downward double slash that detonates on impact. Visual: a gate of flame crashing down.",
 personality="Direct, brave, impatient, respects a Summoner who commits to a choice.",
 quote="Pick a road. I'll burn it clear.", origin="The first card drawn in Silverbrook, bound to the Summoner's hand.",
 bg="Ruined timber fence at the forest edge, embers falling."),
dict(id="B-2", name="Sable", epithet="the Quiet Archer", rank="B", race="Human", gender="female", age=29,
 body="tall, lean and elegant, long limbs, narrow waist", size="Medium", height=172,
 element="Wind", cls="Windbow Scout", role="Support", pri="Sight", sec="Wit", room="Silverbrook Adventure Guild",
 look="Cool, composed. Black hair in a long low braid with a green strip of cloth, pale green-grey eyes, a small mole under the left eye, dry half-smile. Canon: observant, dryly funny, protective in practical ways.",
 palette=["forest green", "charcoal", "silver"],
 battle="Long weathered green coat with wind-stirred hem, fitted tunic, belted shorts over leggings, bracers, quiver, boots, a faint silver-blue thread of Celestium in the lining.",
 casual="Knitted sweater, scarf, soft trousers, wool socks, a cup of tea.",
 work="Scout's vest with map pouches, rolled sleeves, light boots.",
 weapon=("Gale-Mark Bow", "A recurve bow of pale ash wood with a silver wind-sigil carved into the riser and a green cloth strip tied to the limb."),
 passive="Borrowed Breath: restores a little energy to an ally each turn. Visual: green wind swirl.",
 a1="Gale Mark: makes the next attack on a target more certain. Visual: green sigil on the foe.",
 a2="Wind Arrow: ranged Wind hit. Visual: a spiral arrow trail.",
 a3="Cut the Chain: removes an enemy control effect. Visual: a shot severing a chain.",
 ult="Hundred Winds: a volley of arrows that carry energy to all allies. Visual: a rain of green-glowing arrows.",
 personality="Observant, dryly funny, protective, prefers information over heroics.",
 quote="Not a haven yet. A claim.", origin="Second card drawn in Silverbrook; scouts the road before anyone walks it.",
 bg="Misty glassroot forest with tall trees and drifting leaves."),
dict(id="B-3", name="Thalassa Brinegate", epithet="the Tidebound Sentinel", rank="B", race="Tidebound (sea-elf)", gender="female", age=33,
 body="statuesque and broad-shouldered, long legs, strong arms, gill-like markings along the ribs", size="Large", height=200,
 element="Water", cls="Tide Sentinel", role="Tank", pri="Grit", sec="Charm", room="Stone Well",
 look="Deep sea-blue skin with pale pearl freckles, long wave-like teal hair braided with shells, luminous silver eyes, small fin-ears, calm regal expression.",
 palette=["deep teal", "pearl white", "silver"],
 battle="Layered scale-plate bodice with a sea-green sash, pearl-studded pauldrons, short flowing hip cape over fitted shorts, greaves with coral motifs, long gloves, a faint Celestium blue shimmer in the pearls.",
 casual="Draped seashell-print shawl over a simple dress, sandals, pearl hairpins.",
 work="Well-keeper's tunic with rolled sleeves, bare arms, rope belt.",
 weapon=("Brinegate Trident-Shield", "A tall trident with a coral-crown tip and a large round pearl-inlaid shield with engraved waves."),
 passive="Tidal Guard: damage taken partially restored as shield. Visual: water motes ring the shield.",
 a1="Bulwark Wave: shield for all allies. Visual: wave across the party.",
 a2="Trident Thrust: Water hit that lowers enemy attack. Visual: bubbles trail the point.",
 a3="Pearl Barrier: reflects the next attack. Visual: shield turns mirror-bright.",
 ult="Tidal Gate: a colossal wave gate protects the party and crashes on enemies. Visual: a giant arch of water opens behind her.",
 personality="Regal, patient, fiercely protective, secretly homesick.",
 quote="The tide does not ask permission.", origin="Sentinel of a sunken gate who followed the Heart's song inland.",
 bg="Coastal cliff with crashing waves and glowing pearl-light."),
dict(id="B-4", name="Corvin Ashmantle", epithet="the Crow Hexmaster", rank="B", race="Crowfolk (beastfolk)", gender="male", age=41,
 body="gaunt and tall with long limbs, hunched shoulders, feathered forearms", size="Medium", height=177,
 element="Dark", cls="Hexmaster", role="Controller", pri="Wit", sec="Sight", room="Deck Hall",
 look="Sharp beak-like nose, black feather crest, glossy iridescent black-violet feathers on the neck and forearms, pale yellow eyes, a wry smile, small bone charms woven into the hair.",
 palette=["raven black", "violet sheen", "bone"],
 battle="Long feathered coat with a high collar, layered shirt, belt of charms, fingerless gloves, tall boots, a faint blue-silver glow in the charm threads.",
 casual="Loose shirt, vest, comfortable scarf, bare feet.",
 work="Scholar's sleeves, ink-stained fingers, spectacles.",
 weapon=("Raven-Bone Staff", "A tall black staff topped with a small raven skull wrapped in violet cords and hanging charms."),
 passive="Omen: lowers one enemy's defense when he applies a debuff. Visual: black feathers drifting.",
 a1="Murder Mark: marks an enemy and weakens it. Visual: crow silhouettes circle.",
 a2="Hex Cry: reduces enemy attack. Visual: a harsh caw soundwave.",
 a3="Shadow Wings: evade and reposition. Visual: wings of shadow.",
 ult="Murder of Crows: a flock devours enemy buffs and strikes all. Visual: swarm of black birds sweeping the field.",
 personality="Sardonic, scholarly, collector of odd facts, hates being rushed.",
 quote="Every omen has a price. This one's yours.", origin="Hex-scholar who read an omen in the Heart's glow and followed it.",
 bg="Gnarled dead tree in a violet dusk, crows on branches."),

dict(id="A-1", name="Tsukiko Raikami", epithet="the Three-Tail Spark", rank="A", race="Kitsune (fox-folk)", gender="female", age=34,
 body="small and graceful, narrow waist, three fluffy tails, light stance", size="Small", height=158,
 element="Lightning", cls="Thunder Shrine Duelist", role="Striker", pri="Grace", sec="Luck", room="Argent Market",
 look="Silver-white fox ears and three tails tipped with yellow lightning, long pale hair in twin-tails, golden eyes with cracked pupils, mischievous fanged smile, faint whisker marks.",
 palette=["storm yellow", "white", "indigo"],
 battle="Short shrine-maiden-inspired outfit with a cropped white and indigo haori, detached sleeves, short skirt over thigh straps, geta-style boots, thunder-drum charms, subtle silver-violet Celestium thread embroidery.",
 casual="Loose yukata off the shoulder, fan in hand, slippers.",
 work="Shop-keeper's apron over a short kimono, abacus at the belt.",
 weapon=("Raikami Fan-Blades", "A pair of folding steel war-fans painted with thunder clouds, edges sparking with lightning."),
 passive="Static Fox-Fire: every third attack adds a chain lightning hit. Visual: floating blue fox-fires.",
 a1="Fan Flash: fast two-hit strike. Visual: crackling arcs.",
 a2="Thunder Step: dodge and counter. Visual: afterimage with lightning.",
 a3="Kitsune Veil: grants allies a speed boost. Visual: fox-fire swirls.",
 ult="Thunder Shrine Descent: a roaring lightning pillar and gates of thunder strike all enemies. Visual: a torii of lightning crashing down.",
 personality="Teasing, vain, strategic, loves gambling and sweets.",
 quote="Roll the dice. Thunder loves a gambler.", origin="Shrine fox who bet her tails and won a market stall in the bargain.",
 bg="Night shrine steps with paper lanterns and storm clouds."),
dict(id="A-2", name="Seraphine Auric", epithet="the Gilded Cantor", rank="A", race="Celestial (winged-kin)", gender="female", age=33,
 body="tall, willowy and regal, long neck, elegant limbs, detachable ribbon-like light wings", size="Medium", height=175,
 element="Light", cls="Cantor", role="Support", pri="Charm", sec="Grace", room="The Frosted Mug",
 look="Warm golden skin, long wavy platinum hair with gold clips, soft golden eyes, a serene face, small gold halo, gentle smile.",
 palette=["pure white", "gold", "pale rose"],
 battle="Layered white-gold gown with a high slit over fitted leggings, golden shoulder pieces, sash, long sleeves with feather-cut edges, gold-trimmed boots, ribbons of light acting as wings, delicate silver-violet Celestium filigree.",
 casual="Soft cream cardigan over a long skirt, gold slippers, hair clips loose.",
 work="Light apron over a simple dress, a hymn book at the hip.",
 weapon=("Auric Lyre-Staff", "A golden harp-topped staff with strings that glow when plucked, ribbon streamers trailing."),
 passive="Hymn Aura: allies gain regen while she sings. Visual: floating musical notes.",
 a1="Cantor's Chord: heals the party slightly. Visual: ripples of light.",
 a2="Gilded Ward: shield on one ally. Visual: golden ring.",
 a3="Sunburst Note: Light damage and blind. Visual: a bright flash.",
 ult="Dawnchoir: full heal plus attack boost for the party. Visual: a huge golden choir sunrise.",
 personality="Gentle, composed, teases, secretly lonely.",
 quote="Sing with me. The light carries.", origin="Cantor who fell from a cloud-chapel and found warmth at the Mug.",
 bg="Golden cathedral clouds with sunbeams."),
dict(id="A-3", name="Ignatius Vael-Drakon", epithet="the Ember Wall", rank="A", race="Dragonkin", gender="male", age=48,
 body="broad, horned and heavily muscled, thick tail, plated chest", size="Large", height=215,
 element="Fire", cls="Dragon Guardian", role="Tank", pri="Grit", sec="Might", room="Lumber Mill",
 look="Crimson scales with gold chest plates, large curved horns, glowing amber slit eyes, short black mane, a deep scar across the muzzle, calm commanding presence.",
 palette=["crimson", "gold", "charcoal"],
 battle="Heavy dragon-scale plate with golden filigree, wide pauldrons, fur-lined cape, belted kilt, steel greaves, wing-stumps wrapped in banners, faint Celestium blue veins in the gold.",
 casual="Big knitted jumper, loose trousers, a warm cup of ale.",
 work="Sleeveless work tunic, log chain over the shoulders.",
 weapon=("Vael Ember Greatshield", "A huge tower shield forged from dragon scale, carved with a roaring dragon and glowing embers; a short war axe is strapped on the back."),
 passive="Dragon Hide: reduces Fire damage and reflects a small amount. Visual: ember glints on scales.",
 a1="Scale Wall: huge shield. Visual: scales shimmer.",
 a2="Cinder Roar: taunt and burn. Visual: small fire breath.",
 a3="Axe Cleave: heavy hit. Visual: red arc.",
 ult="Dragon's Embrace: a fire barrier protects the party and scorches attackers. Visual: wings of flame unfurl.",
 personality="Gruff, wise, deeply loyal, cooks well.",
 quote="Behind the wall, little ones.", origin="Last guard of a fallen dragon-keep who swore his shield to the Heart.",
 bg="Volcanic ridge at dusk, embers floating."),
dict(id="A-4", name="Maelor Deepvein", epithet="the Quarry Colossus", rank="A", race="Stone-giant", gender="male", age=60,
 body="gigantic, craggy and thick, arms like pillars, slow and deliberate", size="Large", height=228,
 element="Earth", cls="Geomancer", role="Controller", pri="Wit", sec="Sight", room="Stone Quarry",
 look="Rough grey-brown stone-textured skin with glowing amber veins, mossy beard, deep-set glowing eyes, calm wise expression, small flowers sprouting from the shoulders.",
 palette=["stone grey", "amber", "moss green"],
 battle="Rough-hewn stone plates, leather harness, large cloak of moss and vines, bracers with etched runes, cloth wraps on legs, a faint blue-silver Celestium glow within the stone veins.",
 casual="Huge wool poncho, no helmet, a bowl of tea in his big hands.",
 work="Open vest, huge rope belt, a hammer and chisel at the hip.",
 weapon=("Deepvein Rune-Staff", "A massive staff of dark stone with carved runes and a heart-shaped amber crystal at the top."),
 passive="Ground Truth: terrain effects he places last longer. Visual: glowing amber runes beneath him.",
 a1="Stone Lock: roots an enemy. Visual: rocks encase feet.",
 a2="Tremor Field: slows all enemies. Visual: cracked ground.",
 a3="Pillar Strike: heavy Earth hit. Visual: a stone pillar.",
 ult="Tectonic Verdict: the ground rises to crush and pin all enemies. Visual: giant rock walls close in.",
 personality="Wise, slow to speak, collects flowers, a patient storyteller.",
 quote="Mountains remember. Let me remind them of you.", origin="Giant who slept in the quarry for centuries until the Heart's hum woke him.",
 bg="Giant quarry cavern, amber light and mossy rocks."),
]
