# 24 residents (non-combatant tower specialists). Fixed rank per resident.
RESIDENTS = [
dict(id="R-01", name="Tobias Rake", epithet="the Hopeful Farmhand", rank="F", race="Human", gender="male", age=26,
 body="lanky, sunburnt and slightly stooped, big feet, long arms", size="Medium", height=174, stat="Grit", room="Farmstead",
 look="Narrow freckled face, sandy hair under a straw hat, brown eyes, shy lopsided smile.",
 palette=["straw yellow", "faded green", "soil brown"],
 casual="Patched flannel shirt, loose trousers, suspenders, bare feet in sandals.",
 work="Sleeveless farm vest over a rolled-sleeve shirt, kneepads, a seed pouch, mud-spattered boots.",
 tool=("Seed Dibber & Watering Can", "A wooden dibber stick and a dented tin watering can painted with a smiling sun."),
 perk="Green Thumb: Farmstead cycles finish slightly faster.",
 personality="Earnest, clumsy, talks to the crops.", quote="They grow better if you sing.", origin="Orphan farmhand who followed the glow to the tower.",
 bg="Sunny farm plot with rows of sprouts."),
dict(id="R-02", name="Mina Dewlight", epithet="the Well-Carrier", rank="F", race="Halfling", gender="female", age=28,
 body="short, sturdy and round-faced, strong shoulders from carrying water", size="Small", height=122, stat="Might", room="Stone Well",
 look="Rosy cheeks, curly brown hair in two buns, wide hazel eyes, quick bright laugh.",
 palette=["sky blue", "cream", "wood brown"],
 casual="Knitted jumper dress, striped stockings, clogs.",
 work="Sleeveless blue tunic, a carrying yoke across the shoulders, rolled trousers, wooden clogs.",
 tool=("Carrying Yoke & Buckets", "A shaped wooden yoke with two oak buckets, one painted with a water drop."),
 perk="Steady Draw: Stone Well yields a little extra Water.",
 personality="Cheerful, strong for her size, always humming.", quote="Careful, it's full!", origin="Village well-girl who walked a day to join the tower.",
 bg="Stone well in a green courtyard, morning mist."),
dict(id="R-03", name="Gorm Hatchet", epithet="the Gentle Logger", rank="F", race="Orc", gender="male", age=33,
 body="huge, broad and muscular with a soft round belly", size="Large", height=200, stat="Might", room="Lumber Mill",
 look="Green-grey skin, small lower tusks, shaved head with a single braid, mild brown eyes, scarred forearms, friendly smile.",
 palette=["forest green", "red plaid", "bark brown"],
 casual="Oversized plaid shirt, rolled trousers, slippers, a tiny carved bird.",
 work="Sleeveless plaid vest, leather harness for logs, heavy gloves, boots.",
 tool=("Felling Axe", "A broad double-bit felling axe with a long ash handle wrapped in red cloth."),
 perk="Timberman: Lumber Mill produces extra Firewood.",
 personality="Soft-spoken, loves carving, cries at sad songs.", quote="Timber... sorry, tree.", origin="Orc logger who put down his axe against people, kept it for trees.",
 bg="Forest clearing with stacked logs and sawdust."),
dict(id="R-04", name="Wren Kettle", epithet="the Steam Cook", rank="F", race="Human", gender="female", age=32,
 body="average height, comfortably curvy, strong forearms", size="Medium", height=165, stat="Grit", room="Kitchen",
 look="Round smiling face, messy dark bun with a wooden spoon in it, flour on the nose, warm brown eyes.",
 palette=["tomato red", "cream", "copper"],
 casual="Loose cardigan, long skirt, house slippers.",
 work="Cook's apron over a short-sleeved blouse, rolled skirt, a kerchief on the head.",
 tool=("Copper Stockpot", "A big dented copper stockpot with a wooden ladle hanging from a hook on the rim."),
 perk="Hearty Meals: Kitchen output is slightly boosted.",
 personality="Bustling, motherly, scolds you into eating.", quote="Sit. Eat. Talk after.", origin="Inn cook who lost her inn to a storm.",
 bg="Warm steamy kitchen with hanging herbs."),
dict(id="R-05", name="Hobb Ledgerfoot", epithet="the Penny-Counter", rank="E", race="Halfling", gender="male", age=45,
 body="short, round-bellied, nimble fingers", size="Small", height=118, stat="Charm", room="Argent Market",
 look="Round jovial face, thin mustache, round spectacles, tidy side-parted grey hair, bright smile.",
 palette=["burgundy", "gold", "cream"],
 casual="Waistcoat with pocket watch, rolled sleeves, slippers.",
 work="Merchant's vest and bow tie, sleeve garters, an abacus on a cord, polished shoes.",
 tool=("Brass Abacus", "A polished brass abacus with colored beads and a leather strap."),
 perk="Fair Haggle: Argent Market earns a little extra Gold.",
 personality="Polite, shrewd, cannot resist a bargain.", quote="A fair price is a friendly price.", origin="Traveling trader who found a permanent stall.",
 bg="Bustling market stall with awnings and crates."),
dict(id="R-06", name="Sera Quickneedle", epithet="the Hearth Seamstress", rank="E", race="Elf", gender="female", age=88,
 body="slim and graceful with long limbs", size="Medium", height=172, stat="Grace", room="Hearth Nursery",
 look="Long straight silver-blonde hair braided over one shoulder, sage-green eyes, delicate pointed ears, a serene smile, needle tucked in the hair.",
 palette=["sage green", "cream", "dusty rose"],
 casual="Layered linen dress with a shawl, slippers.",
 work="Seamstress apron with pockets, pincushion on the wrist, rolled sleeves.",
 tool=("Silver Needle Case", "A slim carved wooden case holding silver needles and bright spools of thread."),
 perk="Soft Stitch: Hearth Nursery children recover and grow slightly faster.",
 personality="Calm, precise, hums lullabies.", quote="Hold still. I've almost got the hem.", origin="Elven tailor who left a cold court for warm company.",
 bg="Cozy sewing nook with hanging fabrics."),
dict(id="R-07", name="Dunstan Pickaxe", epithet="the Stonecutter", rank="E", race="Dwarf", gender="male", age=58,
 body="short, broad and muscular, thick forearms", size="Small", height=135, stat="Might", room="Stone Quarry",
 look="Ruddy cheeks, braided red-brown beard with iron rings, bushy brows, deep blue eyes, dust in the hair.",
 palette=["slate grey", "rust", "leather brown"],
 casual="Woolen jumper, trousers, a pipe, slippers.",
 work="Leather apron, sleeveless shirt, hard cap, stonecutter's gloves.",
 tool=("Stonecutter's Pick", "A worn iron pick with a wooden handle and a chisel tucked into the belt."),
 perk="Fine Chisel: Stone Quarry output is slightly higher.",
 personality="Gruff, hard-working, hums mining songs.", quote="Nothing breaks like honest rock.", origin="Dwarf miner who prefers daylight work.",
 bg="Quarry face with chiseled blocks."),
dict(id="R-08", name="Lio Marigold", epithet="the Garden Hare", rank="E", race="Hare-folk (beastfolk)", gender="male", age=27,
 body="tall, lean with long legs and large feet", size="Large", height=190, stat="Grit", room="Farmstead",
 look="Light brown fur with a white belly, long drooping ears with flower clips, soft hazel eyes, a gentle nose twitch, shy smile.",
 palette=["marigold orange", "leaf green", "cream"],
 casual="Loose linen shirt, shorts, flower garlands, barefoot.",
 work="Gardener's vest, rolled sleeves, kneepads, trowel belt.",
 tool=("Trowel & Seed Satchel", "A small iron trowel and a satchel stitched with marigold flowers."),
 perk="Quick Sprouts: Farmstead cycles finish slightly faster.",
 personality="Gentle, nervous, full of flower trivia.", quote="They'll bloom, I promise.", origin="Hare-folk gardener who fled a burned orchard.",
 bg="Flower-filled garden with trellises."),
dict(id="R-09", name="Ilsa Brewbright", epithet="the Hearty Innkeeper", rank="D", race="Human", gender="female", age=40,
 body="curvy and strong with broad shoulders", size="Medium", height=170, stat="Charm", room="The Frosted Mug",
 look="Rosy cheeks, auburn curls tied with a ribbon, bright green eyes, laugh lines, warm grin.",
 palette=["amber", "burgundy", "cream"],
 casual="Frilled blouse with a laced bodice, long skirt, slippers.",
 work="Barmaid's apron over a bodice and blouse, rolled sleeves, a towel over the shoulder.",
 tool=("Frosted Tankard Set", "Three stacked frosty pewter tankards with a hammered brass tray."),
 perk="Good Cheer: Frosted Mug boosts satisfaction slightly.",
 personality="Boisterous, motherly, never forgets a name.", quote="First round's on the house. Don't tell the boss.", origin="Innkeeper who inherited the Mug and kept it lively.",
 bg="Warm tavern with crowded tables."),
dict(id="R-10", name="Fenwick Quill", epithet="the Ink-Stained Scribe", rank="D", race="Gnome", gender="male", age=51,
 body="small and slight with ink-stained fingers", size="Small", height=120, stat="Wit", room="Deck Hall",
 look="Big round spectacles, wild white hair, long nose, bright blue eyes, ink on the cheek.",
 palette=["ink blue", "parchment", "bronze"],
 casual="Oversized dressing gown, slippers, a nightcap.",
 work="Scribe's sleeves, waistcoat, spectacles chain, a quill behind the ear.",
 tool=("Quill & Ledger", "A long feather quill and a thick leather-bound ledger with brass corners."),
 perk="Careful Notes: Deck Hall training grants a little extra XP.",
 personality="Fussy, absent-minded, delighted by footnotes.", quote="Citation needed. Oh, I'll cite myself.", origin="Gnome archivist whose library burned.",
 bg="Cluttered scriptorium with stacked scrolls."),
dict(id="R-11", name="Nessa Tidewell", epithet="the Lakeside Healer", rank="D", race="Lakefolk (water-kin)", gender="female", age=34,
 body="tall, graceful and slender with webbed fingers", size="Large", height=188, stat="Grace", room="The Frosted Mug",
 look="Pale blue-green skin, long damp teal hair, soft silver eyes, tiny fin-ears, gentle smile.",
 palette=["lake blue", "pearl", "soft gold"],
 casual="Draped linen gown, bare feet, a shell comb.",
 work="Healer's apron over a simple dress, rolled sleeves, herb basket.",
 tool=("Shell Remedy Bowl", "A wide shell bowl with a wooden pestle and tiny glass vials."),
 perk="Soothing Waters: Frosted Mug produces extra Tonics.",
 personality="Gentle, quiet, hums to the sick.", quote="Drink. The lake remembers you.", origin="Lake healer drawn by the Heart's hum.",
 bg="Misty lakeside with stepping stones."),
dict(id="R-12", name="Brakka Ironsmoke", epithet="the Anvil Matron", rank="C", race="Half-orc", gender="female", age=37,
 body="tall, broad and strongly muscled", size="Large", height=198, stat="Might", room="The Forge",
 look="Grey-green skin, small tusks, tied-back black hair with a red bandana, strong jaw, sooty cheek, proud smirk, burn scars on the forearms.",
 palette=["iron grey", "ember orange", "leather black"],
 casual="Oversized tank top, loose trousers, slippers, a mug of tea.",
 work="Smith's apron over a tank top, heat gloves, goggles on the forehead.",
 tool=("Master's Hammer & Tongs", "A heavy forge hammer with a worn grip and long iron tongs."),
 perk="Hammer Rhythm: Forge training grants a bit more XP.",
 personality="Blunt, motherly, roars with laughter.", quote="Quench it. Don't cry over it.", origin="Smith who earned her anvil in a mercenary camp.",
 bg="Roaring forge with glowing metal."),
dict(id="R-13", name="Odalys Thornfield", epithet="the Orchard Dryad", rank="C", race="Dryad", gender="female", age=140,
 body="slender and medium height, bark patterns along arms and legs", size="Medium", height=168, stat="Grit", room="Farmstead",
 look="Bark-brown skin with moss patches, hair of long green leaves with small flowers, golden-green eyes, calm smile.",
 palette=["moss green", "bark brown", "blossom pink"],
 casual="Loose leaf-woven wrap dress, bare feet, flower crown.",
 work="Sleeveless leaf tunic, gardener's belt, vine gloves.",
 tool=("Pruning Shears & Seed Pouch", "Silver shears with a vine-wrapped handle and a pouch of glowing seeds."),
 perk="Orchard's Gift: Farmstead yields extra Food.",
 personality="Calm, wise, sleeps in sunbeams.", quote="Patience grows everything.", origin="Dryad of a fallen orchard that found a new soil.",
 bg="Blossoming orchard with falling petals."),
dict(id="R-14", name="Cato Lanternjaw", epithet="the Trail Spotter", rank="C", race="Halfling", gender="male", age=36,
 body="short, wiry and quick, big feet", size="Small", height=125, stat="Sight", room="Silverbrook Adventure Guild",
 look="Square jaw with stubble, bright squinting eyes, curly brown hair, a lantern clipped at the belt, confident grin.",
 palette=["trail brown", "lantern yellow", "olive green"],
 casual="Wool jumper, shorts, slippers, a mug of cocoa.",
 work="Scout's vest with map pouches, spyglass at the belt, hooded cloak.",
 tool=("Spyglass & Lantern", "A brass spyglass and a small hooded lantern, both dented but well-polished."),
 perk="Far Sight: Guild expeditions reveal extra info.",
 personality="Chatty, cautious, great with maps.", quote="Trust me. I've been lost here before.", origin="Halfling scout who mapped every ditch in Silverwood.",
 bg="Treetop lookout with a view of the forest."),
dict(id="R-15", name="Yarrow Moss", epithet="the Gentle Sapling", rank="B", race="Treant sprout", gender="female", age=61,
 body="very tall, bark-skinned, thick limbs and a soft rounded frame", size="Large", height=210, stat="Grace", room="Hearth Nursery",
 look="Warm brown bark skin with moss patches, hair of leaves and small white flowers, glowing green eyes, patient smile.",
 palette=["moss green", "warm brown", "cream flower"],
 casual="Oversized knitted shawl, bare feet with roots, a small lullaby bell.",
 work="Nursery apron over bark skin, ribbon in the leaves.",
 tool=("Lullaby Branch", "A small branch with a bell and ribbon, humming softly."),
 perk="Gentle Giant: Hearth Nursery capacity and care speed increase.",
 personality="Very patient, quiet, slow to anger.", quote="Sleep. The forest will keep watch.", origin="A sapling-giant who grew beside the tower.",
 bg="Soft nursery in a tree-hollow with fireflies."),
dict(id="R-16", name="Pell Fortunecoin", epithet="the Lucky Gambler", rank="B", race="Fox-folk (beastfolk)", gender="male", age=33,
 body="small, slim and quick with a long bushy tail", size="Small", height=150, stat="Luck", room="Argent Market",
 look="Orange fur with white cheeks, sly amber eyes, cheeky grin, a coin always spinning in one hand.",
 palette=["gold", "crimson", "orange fur"],
 casual="Open waistcoat, loose shirt, slippers, a lucky clover pinned.",
 work="Dealer's visor, sleeve garters, card shuffler gloves.",
 tool=("Lucky Dice & Coin", "A pair of ivory dice and a gold coin hanging on a ribbon."),
 perk="Windfall: Argent Market sometimes yields bonus Gold.",
 personality="Charming, slippery, honest about being dishonest.", quote="Odds? Never heard of them.", origin="Fox gambler who lost everything and won it back.",
 bg="Glitter-lit gaming table with scattered cards."),
dict(id="R-17", name="Dr. Ambrose Pennywhistle", epithet="the Scholar of Moths", rank="B", race="Human", gender="male", age=53,
 body="average height, slight stoop, thin", size="Medium", height=176, stat="Wit", room="Deck Hall",
 look="Round spectacles, tweed jacket, wild grey sideburns, a dusty moth on the shoulder, bright curious eyes.",
 palette=["tweed brown", "cream", "teal"],
 casual="Dressing gown, slippers, moth-eaten scarf.",
 work="Tweed vest with many pockets, a magnifier on a chain, sleeve garters.",
 tool=("Specimen Case & Magnifier", "A brass-latched specimen case and a magnifying glass on a chain."),
 perk="Research Notes: Deck Hall training grants extra XP.",
 personality="Absent-minded, enthusiastic, gets lost mid-sentence.", quote="Fascinating! Wait, where was I?", origin="Professor who followed a rare moth into the forest.",
 bg="Study with moth specimens and shelves."),
dict(id="R-18", name="Kasimir Veil", epithet="the Silver-Tongued Broker", rank="A", race="Tiefling", gender="male", age=42,
 body="tall, slender with sharp shoulders and a long tail", size="Large", height=192, stat="Charm", room="Argent Market",
 look="Deep violet skin, curved horns with gold caps, slicked-back black hair, golden eyes, trimmed goatee, a charming smile.",
 palette=["violet", "gold", "black"],
 casual="Silk robe, bare feet, a glass of wine, a ring on every finger.",
 work="Tailored waistcoat, coat with golden buttons, a quill-pen and ledger.",
 tool=("Golden Ledger & Scales", "A gold-edged ledger and a tiny brass scale with violet weights."),
 perk="Silver Tongue: Argent Market earns extra Gold and lowers prices.",
 personality="Suave, calculating, secretly generous.", quote="Everything has a price. Let's find yours.", origin="Broker who retired from a gilded city.",
 bg="Opulent trading hall with gold accents."),
dict(id="R-19", name="Mother Hesper", epithet="the Lullaby Elder", rank="A", race="Elf", gender="female", age=240,
 body="slender, elderly yet upright, delicate hands", size="Medium", height=168, stat="Grace", room="Hearth Nursery",
 look="Long silver hair in a loose braid, deep lavender eyes, soft wrinkles, serene smile, a faint glow around the hands.",
 palette=["lavender", "silver", "cream"],
 casual="Layered shawl and long robe, slippers, a candle.",
 work="Apron over a simple robe, a basket of blankets, a rocking chair nearby.",
 tool=("Moonlit Rocking Chair & Blanket", "A carved wooden rocking chair with a woven blanket that glows softly."),
 perk="Moonlit Lullaby: Hearth Nursery births are safer and satisfaction rises.",
 personality="Gentle, wise, mild humor.", quote="Sleep now, little spark.", origin="Elder who sang the tower's first lullaby.",
 bg="Moonlit nursery with soft candles."),
dict(id="R-20", name="Ruvik Glasseye", epithet="the Lens-Grinder", rank="A", race="Goblin", gender="male", age=39,
 body="small and wiry, large ears", size="Small", height=122, stat="Sight", room="Silverbrook Adventure Guild",
 look="Green skin, huge round goggles with multiple lenses, pointed ears, sharp grin, tufts of white hair.",
 palette=["goblin green", "brass", "indigo"],
 casual="Oversized vest, shorts, slippers, tiny lenses in a pocket.",
 work="Leather apron, bandolier of lenses, tool belt.",
 tool=("Master Lens Kit", "A leather case of ground lenses, tiny files and a brass loupe."),
 perk="Sharp Lens: Guild expeditions have greater success chance.",
 personality="Eccentric, fast-talking, proud of his craft.", quote="See? Everything's clearer with the right glass.", origin="Goblin optician who built the Guild's spyglass.",
 bg="Workshop full of lenses and light."),
dict(id="R-21", name="Tamsin Starling", epithet="the Cloverkin Charm", rank="S", race="Cloverkin (fae)", gender="female", age=75,
 body="tiny with delicate limbs and clover-leaf ears", size="Small", height=132, stat="Luck", room="Barn",
 look="Pale green skin with clover freckles, curly green hair with clover clips, bright eyes with four-leaf pupils, cheeky smile.",
 palette=["clover green", "gold", "white"],
 casual="Clover-print dress, slippers, a ribbon.",
 work="Barn-hand overalls, ribbon in the hair, tiny watering can.",
 tool=("Four-Leaf Satchel", "A tiny satchel stitched with four-leaf clovers, full of lucky charms."),
 perk="Lucky Clover: Barn livestock produce bonus goods and storage rolls improve.",
 personality="Bubbly, mischievous, easily bored.", quote="Pick a clover. Any clover!", origin="Cloverkin who hid under a barn and brought luck.",
 bg="Meadow of clover under a rainbow."),
dict(id="R-22", name="Magister Oru", epithet="the Archivist Automaton", rank="S", race="Celestium Automaton", gender="nonbinary", age=22,
 body="tall, slim, polished white and gold frame with an exposed glowing core", size="Large", height=205, stat="Wit", room="Deck Hall",
 look="Smooth white faceplate with a thin cyan visor, soft blue eyes, small antennae, calm expression.",
 palette=["white porcelain", "gold", "cyan"],
 casual="Oversized scarf, slippers, a mug of oil-tea.",
 work="Archivist's coat with scroll pockets, rolled sleeves, a quill-arm attachment.",
 tool=("Archive Core Tablet", "A thin glowing slate tablet with etched constellations and a small floating core."),
 perk="Perfect Memory: Deck Hall research and training are faster.",
 personality="Polite, precise, curious about jokes.", quote="Processing... humor module unavailable.", origin="Automaton archive keeper reawakened by the Heart.",
 bg="Archive hall of glowing shelves."),
dict(id="R-23", name="Sunniva Hearthsong", epithet="the Celestial Cook", rank="SS", race="Celestium-touched human", gender="female", age=39,
 body="tall, strong and full-figured with warm presence", size="Medium", height=176, stat="Grit", room="Kitchen",
 look="Warm skin, golden-brown curls, glowing amber eyes with a Celestium blue ring, radiant smile.",
 palette=["amber", "cream", "silver-violet"],
 casual="Soft knit dress with an apron, slippers, hair loose.",
 work="Silver-trimmed chef's apron over a blouse, rolled sleeves, a sprig of herbs.",
 tool=("Celestium Cooking Hearth Pot", "A big pot with silver rim and a glowing Celestium core underneath."),
 perk="Starlight Feast: Kitchen output rises and boosts satisfaction.",
 personality="Radiant, generous, a little proud of her recipes.", quote="Eat. Even the stars get hungry.", origin="Cook whose stew once saved a starving village.",
 bg="Golden kitchen with a glowing hearth."),
dict(id="R-24", name="Elder Ysolde Everwell", epithet="the Wellspring Spirit", rank="SSR", race="Wellspring spirit", gender="female", age=500,
 body="tall, ethereal and flowing with translucent water-limbs", size="Large", height=215, stat="Might", room="Stone Well",
 look="Translucent blue skin with swirling water inside, long flowing silver-blue hair, glowing aqua eyes, serene smile, a crown of crystal droplets.",
 palette=["aqua", "silver", "celestium violet"],
 casual="Draped water-silk robe, bare feet, floating droplets.",
 work="Water-silk apron with floating droplets, a ladle in hand.",
 tool=("Everwell Chalice", "A silver chalice with a contained Celestium crystal and a never-empty spring of water."),
 perk="Everwell: Stone Well is never empty and gives all rooms a bit of Water bonus.",
 personality="Calm, ancient, gentle, loves tea.", quote="Drink deeply. The well remembers.", origin="Ancient spirit of a spring beneath the tower.",
 bg="Glowing underground spring with crystals."),
]
